on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
permissions:
  contents: write
  pull-requests: write
name: All actions
env:
  R_KEEP_PKG_SOURCE: true
  POSTGRES_PW: ${{secrets.TEST_POSTGRES_DB_PW}}
jobs:
  check-current-version:
    name: Check current version
    uses: >-
      NovoNordisk-OpenSource/r.workflows/.github/workflows/check_current_version.yaml@update_lynchee
    with:
      use_local_setup_action: true
  pkgdown:
    name: Pkgdown site
    uses: NovoNordisk-OpenSource/r.workflows/.github/workflows/pkgdown.yaml@update_lynchee
    with:
      use_local_setup_action: true
  coverage:
    name: Coverage report
    uses: NovoNordisk-OpenSource/r.workflows/.github/workflows/coverage.yaml@update_lynchee
    secrets: inherit
    with:
      use_local_setup_action: true
      use_codecov: true
  megalinter:
    name: Megalinter
    uses: NovoNordisk-OpenSource/r.workflows/.github/workflows/megalinter.yaml@update_lynchee
